### ISSUE TITLE
Future events

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/DocCalendar#1]
Instead of the "`createdon`" date, possibly us a TV with date input.
This would allow upcoming events/dates to be displayed.
Similar to the [Kalender](https://modx.com/extras/package/kalenderenhanced) extra.

**Comment by Nicola1971** [comment]
was very busy this days, and has got no time to publish ad write docs for DocCalendar.

**Yes, you can do  :)**

* Create two date tvs ie: Start-Date and End-Date 
Important: set date-format for both tvs to **%Y-%m-%dT%H:%M:%S**

* in your DocCalendar-Tpl: 

`start: '[+Start-Date+]',`

`end: '[+End-Date+]' `

Today i've updated a bit the snippet, published and started documentation: 
http://www.tattoocms.it/extras/snippets/doccalendar.html

**Comment by risingisland** [comment]
Looks and works great.
I didnt have the date-format correct before.

Line 15 of "DocCalendar.tpl"
`$locale = isset($locale) ? $locale : 'eng';` 
should be changed to:
`$locale = isset($locale) ? $locale : 'en-gb';` 

Or some other working lang.
Everything else is awesome, including demo page ;)

**Comment by Nicola1971** [comment]
Thanks :)
added your fix to https://github.com/Nicola1971/DocCalendar/commit/691f2e3f4e35945a4724f2d9d4cd292af4922762

**Comment by Nicola1971** [comment]
closed
