### ISSUE TITLE
New options added

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/DocCalendar#2]
Added a few new "view" options with button fields to accommodate them in Snippet.
Added new TV "Event Date".
Edited Chunk to use TV.

[install.zip](https://github.com/Nicola1971/DocCalendar/files/644431/install.zip)

**Comment by Nicola1971** [comment]
ok, for added views.

About chunks and tvs:

We can include two tpl chunks examples:
1) BlogCalendar.tpl (with createdon/publishedon as source date) to create blog archives calendars
2) EventCalendar.tpl (with tvs as source date) to create events calendars

**Comment by risingisland** [comment]
Sounds good.

**Comment by Nicola1971** [comment]
added in RC1.1
